export const EmailTypes = [
  "custom",
  "gameTimeChanged",
  "interest",
  "invalidGames",
  "lockedOut",
  "newUser",
  "passwordReset",
  "pickReminder",
  "picksAutoSubmitted",
  "picksSubmitted",
  "prizesSet",
  "quickPick",
  "quickPickConfirmation",
  "survivorEliminated",
  "survivorReminder",
  "trusted",
  "untrusted",
  "weekly",
  "weekEnded",
  "weekStarted",
] as const;
